### PR TITLE
Fix broken anchor links (#464, #465)

### LINKED ISSUE #464: #anchor links to references items are ungrouped for @see and @alias annotations
If I assign an `@see` or `@alias` within the comment block, and the item it's referencing is documented as being inside a `@group` then the Core doesn't seemingly return anything useable to the theme it can use to correctly construct the correct #group-type-name reference.

This occurs regardless of if I assign the `@group` annotation at a file or definition level.

Going on the default theme file /views/includes/annotations/see.html.swig, I'd perhaps expect to be able to do something like

```
<li><span class="item__cross-type">[{{ see.context.type }}]</span> <a href="#{{ see.group }}-{{ see.context.type }}-{{ see.context.name }}"><code>{{ see.context.name }}</code></a></li>
```

Unless of course I'm missing something obvious, and the JS that resolves the value object this annotation template uses does actually return such a property?

### PR DESCRIPTION
**Pull request by valeriangalliat**
Rebased version of #465 with addressed PR comments.

Fixes #464, closes #465.

### CODE REVIEW

File: src/annotation/annotations/alias.js [hunk 1]
```diff
@@ -14,6 +14,7 @@ export default function alias (env) {
 
         let alias = item.alias
         let name = item.context.name
+        let aliasGroup = item.group
 
         let aliasedItem = Array.find(data, i => i.context.name === alias)
```
Comment (d13) [inline src/annotation/annotations/alias.js:19]: This lookup finds the **_first_** instance of the alias name, which could be incorrect if there's more than one context with the same name.

**Review by d13 — COMMENTED** [review]
I was able to use the group by adding the a `{{group_name}}` to `see.html.njk` in `sassdoc-theme-default`:

```
    {% set group_name = '' %}
    {% if see.group %}
      {% set group_name = see.group + '-' %}
    {% endif %}

    <li><span class="item__cross-type">[{{ see.context.type }}]</span> <a href="#{{ group_name }}{{ see.context.type }}-{{ see.context.name }}"><code>{{ see.context.name | unescape }}</code></a></li>
```

That being said, its highly likely to give the incorrect group if there's more than on context with the same name. I commented on the line that does the lookup, which is prior to this change.

**Comment by valeriangalliat** [comment]
@d13 thanks for reviewing!

So my understanding is that this solution is not perfect but still yields better results than if we don't land it. Also it needs extra theme code to be useful.

What I can do is:

* Add that code of yours to `sassdoc-theme-default` and release a new patch version with it (feel free to open a PR there if you want the commit attribution ☺️)
* Merge this PR as is and release a new patch version

Does that sounds good?

---

As for the alias issue when multiple contexts share the same name, I'm not sure from the top of my head how that can be fixed (haven't worked with SassDoc in the past... many years) but I'll definitely accept a PR for it!

**Comment by kdaulton-chwy** [comment]
@valeriangalliat thanks!

I'll definitely put up the PR for `sassdoc-theme-default`. 

I'll also put some time into how to solve the alias with same name issue.

**Comment by valeriangalliat** [comment]
Great! Thanks for the PR on sassdoc-theme-default

This is released with sassdoc@2.7.4
